### ISSUE TITLE
incorrect username or password

### ISSUE THREAD

**Issue by taylorty** [Ma63d/leetcode-spider#1]
请教一下 我试了好几次都是incorrect username or password, 试了两个账户都是这个error，username和password应该都没错，不知道是哪里出了问题

**Comment by Ma63d** [comment]
你好，我测试了一下，发现出问题了，确实是这样
估计是leetcode登陆策略有什么改动了，我先debug看看

**Comment by Ma63d** [comment]
找到bug了，应该是这两天leetcode又改了反爬虫的策略了，我周末还用着没有问题
之前在进入到登陆页的时候，leetcode会给cookie里面注入一条`csrftoken`，提交登陆的表单的时候不仅要提交账号密码，还要把这条csrftoken也提交了。
现在的情况是他在dom里插入了一条隐藏的input项：csrfmiddlewaretoken，现在提交表单需要带的是这个csrfmiddlewaretoken，同时保证cookie里面有csrftoken。
我先去改改代码。

**Comment by Ma63d** [comment]
@taylorty 你好，bug已经修复 
```
npm update leetcode-spider -g
```
升级一下leetcode-spider就可以继续使用了

**Comment by taylorty** [comment]
可以用了，太感谢了！修bug速度很快。感谢制作这么有用的爬虫！

**Comment by Ma63d** [comment]
@taylorty 哈哈，没事，也希望你在使用过程中如果有什么需求和优化的建议，可以随时开issue告诉我，毕竟我个人的使用场景和使用习惯有限，
