### ISSUE TITLE
请问一下支持按照tag进行分类吗

### ISSUE THREAD

**Issue by morethink** [Ma63d/leetcode-spider#13]

**Comment by yijieqiu** [comment]
试了一下[这里](https://github.com/Ma63d/leetcode-spider/blob/master/lib/spider.js#L140)用到的API, 返回结果里面并没有tag或company的信息。用developer tool简单看了一下点击某个tag之后的request，tag和company好像都是用GraphQL包装起来的，而不是一个直接可用的API.
本来也有一样的疑问，但现在看来tag分类暂时做不到呀 :(

**Comment by Ma63d** [comment]
项目已不再维护，见首页 README.md ，抱歉。
