### ISSUE TITLE
可以运行，但是爬下来只有题目，没代码呀？

### ISSUE THREAD

**Issue by ZeroZeroOne** [Ma63d/leetcode-spider#2]
如图
![image](https://cloud.githubusercontent.com/assets/21981767/25485034/e46fa018-2b8e-11e7-8bc9-448b5ea7cfbe.png)
麻烦你了，因为我不太会这些。

**Comment by Ma63d** [comment]
纳尼？ 我没仔细看，看来是还有问题。那你再等一下，我今晚回去再debug一下。

**Comment by Ma63d** [comment]
复现了一下，确实有问题。leetcode时不时改接口结构。

**Comment by ZeroZeroOne** [comment]
我看好像不支持C++呀。。。楼主你可不能看不起我们C++

**Comment by Ma63d** [comment]
别闹老铁，![](http://oddbl4fim.bkt.clouddn.com//17-4-27/96598155-file_1493302417357_274a.png)
我特么支持的第一个语言就是你们大C++！
自己看：https://github.com/Ma63d/leetcode-spider/blob/master/lib/language.js#L3

**Comment by Ma63d** [comment]
@ZeroZeroOne  已经fix了。更新一下吧。

**Comment by ZeroZeroOne** [comment]
@Ma63d 可以了，但是真的爬取不了C++，每道题我都是用Python和C++刷2遍，但是只有python代码，
![image](https://cloud.githubusercontent.com/assets/21981767/25519358/1647211a-2c2a-11e7-80b0-77486b8832c8.png)

**Comment by Ma63d** [comment]
纳尼？ 不应该啊 我没对c++做什么特殊处理啊，等等哈。你在config.json里面写了

**Comment by ZeroZeroOne** [comment]
写了
"language": ["c++","python"]

**Comment by Ma63d** [comment]
tmd leetcode在ajax返回的json里面把‘c++‘改为了‘cpp’
现在应该可以了，删了result.json然后npm update一下再试试。
