### ISSUE TITLE
Difficulty level显示不正确

### ISSUE THREAD

**Issue by taylorty21** [Ma63d/leetcode-spider#5]
最近爬下来的题的难度指数不太对，和lc网站上显示的有出入 
easy的题会显示成hard，medium的题会显示成easy

**Comment by Ma63d** [comment]
好的，多谢反馈，应该又是 leetcode 改了数据格式，今晚我 debug 一下。

**Comment by Ma63d** [comment]
@taylorty21 我试了一下，没有任何问题啊，请给出具体错误的题号。

**Comment by taylorty21** [comment]
https://leetcode.com/problems/symmetric-tree/#/description
Easy显示成了Hard
https://leetcode.com/problems/delete-node-in-a-linked-list/#/description
这题也是

**Comment by Ma63d** [comment]
我这边没有这个情况诶，我看了下数据接口，这个数据的返回也是没有变动的。
另外因为这个数据并不是手动生成的，所以不太可能出现某几道题的 difficulty 单独出错的情况。我只能认为是你在进行爬取的时候， leetcode 返回的数据出错了。
所以麻烦删除下 result.json 文件后重试一下。
另外，`hard` 应该显示为 `Hard`，已修复，可以 npm update 一下。

**Comment by Ma63d** [comment]
![](http://oddbl4fim.bkt.clouddn.com//17-6-14/65720963.jpg)

**Comment by Ma63d** [comment]
@taylorty21 请问还有这种情况吗？能否复现？

**Comment by taylorty21** [comment]
删除result.json重新爬解决了问题，多谢

**Comment by taylorty21** [comment]
问题没有重复出现

**Comment by Ma63d** [comment]
@taylorty21 嗯，没问题了就好。
