### ISSUE TITLE
语言GO的没有抓取成功

### ISSUE THREAD

**Issue by to2false** [Ma63d/leetcode-spider#6]
运行未出错，但是没有solution，只有问题的描述

**Comment by Ma63d** [comment]
好的，我看看哈

**Comment by Ma63d** [comment]
@to2false  应该是已经 fix 了，麻烦 npm update 更新一下之后删除 result.json 文件，重新再爬一下试试。

**Comment by to2false** [comment]
已测试，问题已修复
